presentation/src/main/java/com/moez/QKSMS/feature/main/MainViewModel.kt
solves origin:
https://github.com/moezbhatti/qksms/pull/1786
=> adds solution

presentation/src/main/res/values/strings.xml
=> chore: closes #78

presentation/src/main/res/values-pl/strings.xml
No need to keep it short.
Thank you for developing this lovely app!!! :-)
=> Updated Polish translation

domain/src/main/java/com/moez/QKSMS/util/Preferences.kt, presentation/src/main/java/com/moez/QKSMS/common/util/TextViewStyler.kt, presentation/src/main/res/values/strings.xml
thank you! =) let me know when it's ready.
=> add 'super' font size setting

presentation/src/main/java/com/moez/QKSMS/common/util/extensions/ViewExtensions.kt, presentation/src/main/res/layout/message_list_item_in.xml, presentation/src/main/res/layout/message_list_item_out.xml
changes to enable "Select and copy a text part" on message list items via double tap on message item. implements solution for https://github.com/octoshrimpy/quik/issues/178
=> [ FEAT REQ ] Select and copy a text part #178

data/src/main/java/com/moez/QKSMS/repository/ConversationRepositoryImpl.kt
satisfies feature request https://github.com/octoshrimpy/quik/issues/138
=> sort blocked messages by lastmessage.date desc

.github/workflows/build-on-pull.yml
Hi;
This PR introduces the project build, and tests the build at each PR, regardless of the branch selected to push this PR.
Close: https://github.com/octoshrimpy/quik/issues/223
=> [Proposal][Workflow] Build on pull request

metadata/fr-FR/full_description.txt, metadata/fr-FR/short_description.txt, metadata/fr-FR/title.txt, presentation/src/main/res/values-fr/strings.xml
Hi;
The purpose of this PR is to update and rectify Quik's French translation, 
and to add Quik's French description for application stores.
* Modified files: _(in presentation/src/main/res/values-fr/)_
- Strings.xml
* Added files: _(in /metadata/fr-FR/)_
- full-description.txt
- short-description.txt
- title.txt
If there's an error somewhere, let me know and I'll make the necessary changes.
Thank you for your time.
=> [Proposal][Update] French translation

presentation/src/main/res/values-fr/strings.xml
build fix. fix incorrect <string> tag in fr strings. changed to <plurals>
=> fix fr strings from pr 226. fixes build

presentation/src/main/res/values-fr/strings.xml
Hi,
this PR aims to correct several errors (forgotten translations and apostrophe without \), this can follow @gavine99's PR (thanks you a lot)
My apologies, thank you.
=> Update french translation

presentation/src/main/java/com/moez/QKSMS/feature/blocking/numbers/BlockedNumbersPresenter.kt
fix bug in unblock number that crashed app by attempting to execute realm transaction on main thread. moved transaction(s) to execute on io thread.
=> fix unblock number bug

presentation/src/main/res/layout/message_list_item_in.xml, presentation/src/main/res/layout/message_list_item_out.xml
compose message_list_item_in/out layout changes to select full background when message selected
from
to
=> fully select message backgrounds in compose screen

presentation/src/main/java/com/moez/QKSMS/feature/compose/AttachmentAdapter.kt
changes to gracefully handle a failure to get contact attachment data from provider
=> gracefully handle a failure to get contact attachment data

data/src/main/AndroidManifest.xml, data/src/main/java/com/moez/QKSMS/manager/BluetoothMicManager.kt, data/src/main/java/com/moez/QKSMS/manager/MediaRecorderManager.kt, presentation/src/main/java/com/moez/QKSMS/feature/compose/ComposeActivity.kt, presentation/src/main/java/com/moez/QKSMS/feature/compose/ComposeView.kt, presentation/src/main/java/com/moez/QKSMS/feature/compose/ComposeViewModel.kt, presentation/src/main/res/layout/compose_activity.xml
changes to record audio from bluetooth sco device (ie bluetooth headset or earbuds) if connected at time of record. no settings or choosing... if a bluetooth sco device is attached at time of starting an audio record, it is used automagically.
whilst the bluetooth is being switched to sco mode (if it, in fact, needs to be switched which takes maybe 150ms-200ms on my device), a bluetooth symbol is briefly displayed in place of the big, wavey record button to notify the user;
* i've found the audio quality recorded through my earbuds is far superior than that captured using the built-in mic
=> use bluetooth sco source device, if available, to record audio

presentation/src/main/res/values/strings.xml
Pretty small fix that was brought up in Matrix.
=> Fix Copyright Date

README.md
Sorry, this fixes a dead link in the readme, caused by #309.
=> Fix Dead Link

presentation/src/main/java/com/moez/QKSMS/feature/compose/ComposeActivityModule.kt
fix to handle sms:12345678?body=hello%20there style intent data uri for compose activity start
old, 2019 code for sms:12345678 style intent data uri handling was breaking with newer style android screenshot share intent
closes https://github.com/octoshrimpy/quik/issues/323
=> fix for handling sms:1234566?body=xyz style uris starting compose activity

presentation/build.gradle
=> Remove `DependencyInfoBlock` in APK

presentation/src/main/res/values-pl/strings.xml
=> Update for Polish translation

presentation/src/main/java/com/moez/QKSMS/feature/compose/ComposeActivity.kt, presentation/src/main/java/com/moez/QKSMS/feature/compose/ComposeView.kt, presentation/src/main/java/com/moez/QKSMS/feature/compose/ComposeViewModel.kt, presentation/src/main/java/com/moez/QKSMS/feature/main/MainActivity.kt, presentation/src/main/res/layout/compose_activity.xml, presentation/src/main/res/layout/conversation_list_item.xml, presentation/src/main/res/layout/main_activity.xml
Closes #48 
Tested on my Kyocera KY-42C
=> Improve d-pad support

data/src/main/java/com/moez/QKSMS/worker/HousekeepingWorker.kt
fixes a bug where housekeeping worker was using a static value for 'remove filers older than' time. now uses time value that is calced when used
=> fix housekeeping worker using a pre-calced, static value for 'delete files older than'

domain/src/main/AndroidManifest.xml
Finished #394. My apologies for updating so soon, I missed this when working on #394. This will make sure all functionality works on the debug build.
=> Change a hardcoded name to a variable

presentation/src/main/java/com/moez/QKSMS/feature/compose/ComposeActivity.kt, presentation/src/main/java/com/moez/QKSMS/feature/compose/ComposeView.kt
a small clean-up of some old code from a non-implemented test feature from a different pr which was commented out but left in the codebase.
a small refactor too.
=> remove some old commented-out, test code and one small refactor

common/src/main/java/com/moez/QKSMS/compat/TelephonyCompat.kt, data/src/main/java/com/moez/QKSMS/repository/ConversationRepositoryImpl.kt, domain/src/main/java/com/moez/QKSMS/interactor/SendMessage.kt, domain/src/main/java/com/moez/QKSMS/repository/ConversationRepository.kt, presentation/src/main/java/com/moez/QKSMS/feature/blocking/numbers/BlockedNumbersPresenter.kt, presentation/src/main/java/com/moez/QKSMS/feature/compose/ComposeViewModel.kt
change compose sendintent (sending sms/mms) and sendmessage interactor to ensure convos congruency
change compose selectedconversation (chips -> convo monitoring) to take advantage of changes in conversationrepo
conversationrepo change getthreadid to getconversation to avoid duplicate db access
some cleanups and refactoring in conversationrepo
=> message send -> convos congruence and chip->convo monitoring improvements

presentation/src/main/java/com/moez/QKSMS/common/util/extensions/ConversationExtension.kt, presentation/src/main/java/com/moez/QKSMS/common/util/extensions/RecipientExtensions.kt
This should fix the problem reported by Gavine in #434 
There was a problem while generating the layout wich caused a null bitmap so I added security just in case to both getThemedIcon functions.
=> Fix null image generation for conversation icons

presentation/src/main/java/com/moez/QKSMS/feature/compose/ComposeViewModel.kt
This was causing an occasional crash. Still not sure why it crashed sometimes, and not others. But this should resolve it. Closes #453.
=> Moved Scheduled Message Toast to main thread.

presentation/src/main/java/com/moez/QKSMS/common/util/NotificationManagerImpl.kt, presentation/src/main/res/values/strings.xml
=> Add a notification action to resend a failed message

data/src/main/java/com/moez/QKSMS/migration/QkRealmMigration.kt, data/src/main/java/com/moez/QKSMS/repository/ScheduledMessageRepositoryImpl.kt, domain/src/main/java/com/moez/QKSMS/interactor/AddScheduledMessage.kt, domain/src/main/java/com/moez/QKSMS/interactor/DeleteScheduledMessages.kt, domain/src/main/java/com/moez/QKSMS/model/ScheduledMessage.kt, domain/src/main/java/com/moez/QKSMS/repository/ScheduledMessageRepository.kt, presentation/src/main/java/com/moez/QKSMS/common/Navigator.kt, presentation/src/main/java/com/moez/QKSMS/feature/compose/ComposeActivity.kt, presentation/src/main/java/com/moez/QKSMS/feature/compose/ComposeState.kt, presentation/src/main/java/com/moez/QKSMS/feature/compose/ComposeViewModel.kt, presentation/src/main/java/com/moez/QKSMS/feature/conversations/ConversationsAdapter.kt, presentation/src/main/java/com/moez/QKSMS/feature/main/MainViewModel.kt, presentation/src/main/java/com/moez/QKSMS/feature/plus/PlusViewModel.kt, presentation/src/main/java/com/moez/QKSMS/feature/scheduled/ScheduledActivity.kt, presentation/src/main/java/com/moez/QKSMS/feature/scheduled/ScheduledActivityModule.kt, presentation/src/main/java/com/moez/QKSMS/feature/scheduled/ScheduledMessageAdapter.kt, presentation/src/main/java/com/moez/QKSMS/feature/scheduled/ScheduledMessageAttachmentAdapter.kt, presentation/src/main/java/com/moez/QKSMS/feature/scheduled/ScheduledState.kt, presentation/src/main/java/com/moez/QKSMS/feature/scheduled/ScheduledViewModel.kt, presentation/src/main/res/layout/compose_activity.xml, presentation/src/main/res/layout/conversation_list_item.xml, presentation/src/main/res/menu/compose.xml, presentation/src/main/res/values/strings.xml
This is a pretty big change that makes a lot of improvements to scheduled messages. 
**This unfortunately required a database migration, that will prevent some of these features from working on messages scheduled with previous versions.**
Closes #473 
Closes #16 
Probably will close #493
[scheduled-quik.webm](https://github.com/user-attachments/assets/dcf47c43-43b1-4541-9583-411e0710ad43)
=> Rework Scheduled Messages

android-smsmms/build.gradle, build.gradle, common/build.gradle, data/build.gradle, domain/build.gradle, gradle.properties, presentation/build.gradle
Removed deprecated j-center, and commented out dependencies.
=> Clean up gradle files

data/src/main/java/com/moez/QKSMS/migration/QkRealmMigration.kt
Fix realm migration for message content filters. See https://github.com/octoshrimpy/quik/commit/0b2c24a076c6fd57bf1337de5828a7f030d9ec4d#diff-6065d828eab80de6d753415f9667b7e5fa090925c23b53406e3ad0f8d45493ec
=> Fix realm migration for message content filters
