- presentation/src/main/java/com/moez/QKSMS/common/util/DateFormatter.kt
I observed that the space before the AM/PM indicator was really an NBSP which caused the original pattern to not match. This pattern, which uses `\s` instead, should match any type of spacing.
> Properly remove AM/PM indicator

- data/src/main/java/com/moez/QKSMS/manager/WidgetManagerImpl.kt
- data/src/main/java/com/moez/QKSMS/repository/ConversationRepositoryImpl.kt
- domain/src/main/java/com/moez/QKSMS/interactor/UpdateBadge.kt
- domain/src/main/java/com/moez/QKSMS/manager/WidgetManager.kt
- domain/src/main/java/com/moez/QKSMS/repository/ConversationRepository.kt
- domain/src/main/java/com/moez/QKSMS/util/Preferences.kt
- presentation/src/main/java/com/moez/QKSMS/feature/compose/ComposeViewModel.kt
- presentation/src/main/java/com/moez/QKSMS/feature/main/MainViewModel.kt
- presentation/src/main/java/com/moez/QKSMS/feature/settings/SettingsController.kt
- presentation/src/main/java/com/moez/QKSMS/feature/settings/SettingsPresenter.kt
- presentation/src/main/java/com/moez/QKSMS/feature/settings/SettingsState.kt
- presentation/src/main/java/com/moez/QKSMS/feature/widget/WidgetAdapter.kt
- presentation/src/main/res/drawable/ic_unreadattop_all_black_24dp.xml
- presentation/src/main/res/layout/settings_controller.xml
- presentation/src/main/res/values/strings.xml
make unread conversations float at the top of conversation lists (including widget) via a new setting "Unread at the top"
satisfies https://github.com/octoshrimpy/quik/issues/41 and https://github.com/octoshrimpy/quik/issues/208
and largely satisfies https://github.com/octoshrimpy/quik/issues/99 (but continues to also show read messages below unread messages in the widget)
order of conversation list items with the setting turned on is;
- unread
- pinned
- draft
- last message date
per conversations repo code;
val sortOrder: MutableList<String> = arrayListOf("pinned", "draft", "lastMessage.date")
val sortDirections: MutableList<Sort> = arrayListOf(Sort.DESCENDING, Sort.DESCENDING, Sort.DESCENDING)
if (unreadAtTop) {
sortOrder.add(0, "lastMessage.read")
sortDirections.add(0, Sort.ASCENDING) …
> make unread conversations float at the top of conversation lists

- domain/src/main/java/com/moez/QKSMS/util/Preferences.kt
- presentation/src/main/java/com/moez/QKSMS/common/util/TextViewStyler.kt
- presentation/src/main/res/values/strings.xml
re-add "super" font size updates
replaces pr https://github.com/octoshrimpy/quik/pull/200
@octoshrimpy my texttospeech pr overrode the changes in the original super font size. this is those same changes against your latest master branch
> add 'super' font size setting - take 2

- presentation/src/main/java/com/moez/QKSMS/common/util/extensions/ViewExtensions.kt
- presentation/src/main/java/com/moez/QKSMS/feature/compose/ComposeActivity.kt
small changes to GestureDectector usage to fix a race condition on MotionEvents being used after they've been recycled resulting in unpredictable touch event processing
> bug fix for motion events being used after recycled

- presentation/src/main/java/com/moez/QKSMS/feature/compose/ComposeActivity.kt
- presentation/src/main/java/com/moez/QKSMS/feature/compose/ComposeState.kt
- presentation/src/main/java/com/moez/QKSMS/feature/compose/ComposeViewModel.kt
- presentation/src/main/res/layout/compose_activity.xml
- presentation/src/main/res/values/strings.xml
changes to disable reply controls and display a relevant message to the user on compose screen if all other conversation  participant numbers are non-replyable (ie alphanumeric sender id)
satisfies feature request https://github.com/octoshrimpy/quik/issues/94
> disable reply ability to non-replyable messages/conversations

- presentation/src/main/java/com/moez/QKSMS/feature/conversationinfo/ConversationInfoAdapter.kt
- presentation/src/main/java/com/moez/QKSMS/feature/main/MainActivity.kt
- presentation/src/main/java/com/moez/QKSMS/feature/main/MainView.kt
- presentation/src/main/java/com/moez/QKSMS/feature/main/MainViewModel.kt
- presentation/src/main/res/layout/conversation_info_settings.xml
- presentation/src/main/res/layout/text_input_dialog.xml
- presentation/src/main/res/menu/main.xml
- presentation/src/main/res/values/strings.xml
add new 'rename conversation' menu option on main activity when 1 convo selected that allows changing conversation name/title 
* note - no restriction of renaming only group conversations
removed restriction on renaming only group conversations on conversationinfo screen because, ummmm... why restrict renaming to only group convos ??
satisfies issue https://github.com/octoshrimpy/quik/issues/14
> change convo name from main convo activity

- presentation/src/main/java/com/moez/QKSMS/feature/compose/ComposeActivity.kt
- presentation/src/main/java/com/moez/QKSMS/feature/compose/ComposeView.kt
- presentation/src/main/java/com/moez/QKSMS/feature/compose/ComposeViewModel.kt
- presentation/src/main/java/com/moez/QKSMS/feature/compose/MessagesAdapter.kt
- presentation/src/main/java/com/moez/QKSMS/feature/conversations/ConversationsAdapter.kt
- presentation/src/main/java/com/moez/QKSMS/feature/main/MainActivity.kt
- presentation/src/main/java/com/moez/QKSMS/feature/main/MainView.kt
- presentation/src/main/java/com/moez/QKSMS/feature/main/MainViewModel.kt
- presentation/src/main/res/menu/compose.xml
- presentation/src/main/res/menu/main.xml
- presentation/src/main/res/values/strings.xml
added select all actionbar item on main (inc archived) and compose activities. item becomes available when first item selected. menu item toggles select all/select none.
added indefinite timeout to archive snackbar on conversations activity when >= 10 conversations are archived at once. in case of accidental mass archive gives user more time to undo.
added 'show status' menu item on compose activity that does the same as short touching on an item (expands it to show time, etc) but can be applied to multiple selected items at once.
made some actionbar items on conversation/archive and compose screens always displayable to maintain user experience whether one or more items are selected on those screens.
select all allows faster actions for 'mark all (un)read', archive all, delete all, pin …
> select all on conversations and compose screens. new compose 'show status' option

- android-smsmms/src/main/java/com/android/mms/transaction/RetryScheduler.java
- android-smsmms/src/main/res/values/strings.xml
- data/src/main/AndroidManifest.xml
- data/src/main/java/com/moez/QKSMS/extensions/UriExtensions.kt
- data/src/main/java/com/moez/QKSMS/repository/MessageRepositoryImpl.kt
- domain/src/main/java/com/moez/QKSMS/interactor/SendScheduledMessage.kt
- domain/src/main/java/com/moez/QKSMS/model/Attachment.kt
- domain/src/main/java/com/moez/QKSMS/model/MmsPart.kt
- presentation/src/main/AndroidManifest.xml
- presentation/src/main/java/com/moez/QKSMS/feature/compose/AttachmentAdapter.kt
- presentation/src/main/java/com/moez/QKSMS/feature/compose/ComposeActivity.kt
- presentation/src/main/java/com/moez/QKSMS/feature/compose/ComposeActivityModule.kt
- presentation/src/main/java/com/moez/QKSMS/feature/compose/ComposeView.kt
- presentation/src/main/java/com/moez/QKSMS/feature/compose/ComposeViewModel.kt
- presentation/src/main/java/com/moez/QKSMS/feature/scheduled/ScheduledMessageAttachmentAdapter.kt
- presentation/src/main/res/drawable/ic_round_volume_up_24.xml
- presentation/src/main/res/layout/attachment_file_list_item.xml
- presentation/src/main/res/layout/compose_activity.xml
- presentation/src/main/res/layout/scheduled_message_image_list_item.xml
- presentation/src/main/res/values-el/strings.xml
- presentation/src/main/res/values-gd/strings.xml
- presentation/src/main/res/values-lt/strings.xml
- presentation/src/main/res/values-ne/strings.xml
- presentation/src/main/res/values-ta/strings.xml
- presentation/src/main/res/values-tl/strings.xml
- presentation/src/main/res/values-ur/strings.xml
- presentation/src/main/res/values/strings.xml
changes to allow attaching any type of file.
primary use-case is for video and audio attachments but nothing to stop any type of file being attached.
changes also allow any file type (*/*) to be shared to quik.
* non-image files cannot be compressed so be very aware of your providers mmsc mms size limit
satisfies request  https://github.com/octoshrimpy/quik/issues/122
satisfies video part of request https://github.com/octoshrimpy/quik/issues/115
> changes to allow attaching *any* type of file

- data/src/main/java/com/moez/QKSMS/repository/ContactRepositoryImpl.kt
- domain/src/main/java/com/moez/QKSMS/repository/ContactRepository.kt
- domain/src/main/java/com/moez/QKSMS/util/Preferences.kt
- presentation/src/main/java/com/moez/QKSMS/common/util/NotificationManagerImpl.kt
- presentation/src/main/java/com/moez/QKSMS/feature/notificationprefs/NotificationPrefsActivity.kt
- presentation/src/main/java/com/moez/QKSMS/feature/notificationprefs/NotificationPrefsState.kt
- presentation/src/main/java/com/moez/QKSMS/feature/notificationprefs/NotificationPrefsViewModel.kt
- presentation/src/main/res/layout/notification_prefs_activity.xml
- presentation/src/main/res/values/strings.xml
changes to make new message notifications silent if any of the recipients of the new message are not in user's contacts. new setting on settings->notifications page
* everything else operates the same except the new message notification - yes, there is still a notification - will make no sound and not distract your attention
> silent notifications if no recipients are a contact

- presentation/src/main/java/com/moez/QKSMS/feature/compose/ComposeViewModel.kt
fix for 'take a photo' not working.
removed runtime check for WRITE_EXTERNAL_STORAGE at 'take a photo' time which is not required for taking a photo
> bug fix of 'take a photo' not working

- data/src/main/java/com/moez/QKSMS/repository/MessageRepositoryImpl.kt
compression was not being applied to images and gifs.
should satisfy issue https://github.com/octoshrimpy/quik/issues/116
* suggest this bugfix goes into latest beta build so it can be well tested
> fix mms image compression bug not compressing

- data/src/main/java/com/moez/QKSMS/repository/MessageRepositoryImpl.kt
- presentation/src/main/AndroidManifest.xml
enabled WRITE_EXTERNAL_STORAGE permission in app manifest which is required to save mms attachments to media storage.
changed media storage locations from ...../QKSMS to ...../QUIK.
satisfies ticket https://github.com/octoshrimpy/quik/issues/235
this pr gets the existing functionality working again for attachment downloading, _but_ that existing functionality is sub-optimal. new issue https://github.com/octoshrimpy/quik/issues/242 opened to address those sub-optimal aspects in future
> fix bug that disabled download/view of mms attachments

- presentation/src/main/java/com/moez/QKSMS/common/Navigator.kt
- presentation/src/main/java/com/moez/QKSMS/feature/compose/ComposeActivity.kt
- presentation/src/main/java/com/moez/QKSMS/feature/compose/ComposeActivityModule.kt
- presentation/src/main/java/com/moez/QKSMS/feature/compose/ComposeState.kt
- presentation/src/main/java/com/moez/QKSMS/feature/compose/ComposeView.kt
- presentation/src/main/java/com/moez/QKSMS/feature/compose/ComposeViewModel.kt
- presentation/src/main/java/com/moez/QKSMS/feature/scheduled/ScheduledViewModel.kt
changes to enter the compose screen in 'scheduling' mode when launched from the scheduling activity. causes message scheduling to shown be shown after contact is chosen
closes https://github.com/octoshrimpy/quik/issues/18
use schedule message button on scheduled activity;
... select contact (or back button and select none)
... scheduling dialog is shown;
... continue to compose message as normal
> Scheduled messages click doesnt schedule 18

- domain/src/main/java/com/moez/QKSMS/util/Preferences.kt
- presentation/src/main/java/com/moez/QKSMS/common/util/NotificationManagerImpl.kt
- presentation/src/main/java/com/moez/QKSMS/common/util/extensions/ViewExtensions.kt
- presentation/src/main/java/com/moez/QKSMS/feature/compose/ComposeActivity.kt
- presentation/src/main/java/com/moez/QKSMS/feature/compose/ComposeView.kt
- presentation/src/main/java/com/moez/QKSMS/feature/compose/ComposeViewModel.kt
- presentation/src/main/java/com/moez/QKSMS/feature/compose/MessagesAdapter.kt
- presentation/src/main/java/com/moez/QKSMS/feature/settings/SettingsController.kt
- presentation/src/main/java/com/moez/QKSMS/feature/settings/SettingsPresenter.kt
- presentation/src/main/java/com/moez/QKSMS/feature/settings/SettingsState.kt
- presentation/src/main/java/com/moez/QKSMS/feature/settings/SettingsView.kt
- presentation/src/main/res/layout/settings_controller.xml
- presentation/src/main/res/values/strings.xml
changes to add a new setting that allows user to choose to
- allow all message links
- block all message links (including in notifications)
- ask via a dialog box whether the user wishes to proceed
setting defaults to "ask"
When "allow," links render as underlined and are touchable. they go straight to their default activity;
and notifications include system generated actions;
When "block," hyperlinks don't render underlined and are not touchable;
also notifications don't show system generated actions;
When "ask," links render underlined and are touchable. each link will take user to a dialog box;
any link type will cause the dialog box, including telephone number links;
closes https://github.com/octoshrimpy/quik/pull/252
> Disable auto hyperlink (warn link on press) 201

- data/src/main/AndroidManifest.xml
- data/src/main/java/com/moez/QKSMS/extensions/UriExtensions.kt
- data/src/main/java/com/moez/QKSMS/manager/MediaRecorderManager.kt
- data/src/main/java/com/moez/QKSMS/manager/PermissionManagerImpl.kt
- data/src/main/java/com/moez/QKSMS/repository/MessageRepositoryImpl.kt
- domain/src/main/java/com/moez/QKSMS/interactor/SendMessage.kt
- domain/src/main/java/com/moez/QKSMS/manager/PermissionManager.kt
- domain/src/main/java/com/moez/QKSMS/model/Attachment.kt
- presentation/src/main/java/com/moez/QKSMS/common/widget/MicInputCloudView.kt
- presentation/src/main/java/com/moez/QKSMS/feature/compose/ComposeActivity.kt
- presentation/src/main/java/com/moez/QKSMS/feature/compose/ComposeActivityModule.kt
- presentation/src/main/java/com/moez/QKSMS/feature/compose/ComposeAttachmentAdapter.kt
- presentation/src/main/java/com/moez/QKSMS/feature/compose/ComposeState.kt
- presentation/src/main/java/com/moez/QKSMS/feature/compose/ComposeView.kt
- presentation/src/main/java/com/moez/QKSMS/feature/compose/ComposeViewModel.kt
- presentation/src/main/res/layout/compose_activity.xml
- presentation/src/main/res/values/attrs.xml
- presentation/src/main/res/values/strings.xml
adds the ability to record and attach one or more audio messages using the device microphone to capture audio like described in post https://github.com/octoshrimpy/quik/issues/64#issuecomment-2620491633 but... no drag microphone up or left (because no auto-send) - just touch mic to start recording.
- click the mic to start recording... or... choose the new _record an audio message_ item from the attach menu
- click the trash button at any time to ditch the audio recording
- click the attach button at any time to attach to the current message
- click the big stop wavey button to stop recording and see a player
- click the big mic wavey button to start recording again (from scratch, not append)
records in amr wideband format. filename template is 'recorded-{uuid}.3ga'. originally designed …
> Quick voice message 64

- presentation/src/main/res/menu/compose.xml
Fixed showing the copy text details, rather than message details, when the info/details button was held down. This closes #292. This was a problem across all languages.
> Fix wrong string when long-pressing detail button.

- presentation/src/main/java/com/moez/QKSMS/feature/compose/ComposeActivity.kt
- presentation/src/main/java/com/moez/QKSMS/feature/compose/ComposeView.kt
- presentation/src/main/java/com/moez/QKSMS/feature/compose/ComposeViewModel.kt
- presentation/src/main/res/menu/compose.xml
- presentation/src/main/res/values/strings.xml
... when the there is message contents to clear - ie a schedule set, text input or attachment(s) added.
this is stage 1 - but independent of - implementation of my feature request https://github.com/octoshrimpy/quik/issues/296.
ui change is that if you have a schedule set, text input or attachment(s) added then a 'delete' (clear current message) icon becomes visible in the menu bar;
clicking the delete menu icon pops up a confirmation dialog;
if 'clear' is selected in the dialog, then the message is cleared - schedule unset, text cleared, attachments removed - ready for new composition;
> changes to enable a delete/clear menu icon on compose screen

- data/src/main/java/com/moez/QKSMS/repository/ScheduledMessageRepositoryImpl.kt
- domain/src/main/java/com/moez/QKSMS/repository/ScheduledMessageRepository.kt
- presentation/src/main/java/com/moez/QKSMS/common/base/QkRealmAdapter.kt
- presentation/src/main/java/com/moez/QKSMS/feature/compose/ComposeActivity.kt
- presentation/src/main/java/com/moez/QKSMS/feature/compose/ComposeView.kt
- presentation/src/main/java/com/moez/QKSMS/feature/compose/ComposeViewModel.kt
- presentation/src/main/java/com/moez/QKSMS/feature/compose/MessagesAdapter.kt
- presentation/src/main/java/com/moez/QKSMS/feature/conversations/ConversationsAdapter.kt
- presentation/src/main/java/com/moez/QKSMS/feature/scheduled/ScheduledActivity.kt
- presentation/src/main/java/com/moez/QKSMS/feature/scheduled/ScheduledMessageAdapter.kt
- presentation/src/main/java/com/moez/QKSMS/feature/scheduled/ScheduledState.kt
- presentation/src/main/java/com/moez/QKSMS/feature/scheduled/ScheduledView.kt
- presentation/src/main/java/com/moez/QKSMS/feature/scheduled/ScheduledViewModel.kt
- presentation/src/main/res/layout/scheduled_activity.xml
- presentation/src/main/res/menu/compose.xml
- presentation/src/main/res/menu/scheduled_messages.xml
- presentation/src/main/res/values/strings.xml
scheduled messages ui activity now matches the ui of other message listing activities in the app with selection and menu icons instead of menu-dialog.
this is stage 2 - but independent of - implementation of my feature request https://github.com/octoshrimpy/quik/issues/296. it includes prior stage 1 pr https://github.com/octoshrimpy/quik/pull/297.
there is _no loss of functionality from previous_, but can now send now or delete multiple scheduled messages at once.
the scheduled messages ui now has proper title bar and ability to select one or many scheduled messages;
when one or more messages are selected menu items are shown like in other screens; toggle select all/none, delete, copy text, and send now.
both send now and delete have confirmation dialogs;
> changes to bring scheduled messages activity into ui alignment with the rest of the app

- presentation/src/main/java/com/moez/QKSMS/common/Navigator.kt
- presentation/src/main/java/com/moez/QKSMS/feature/compose/ComposeActivityModule.kt
- presentation/src/main/java/com/moez/QKSMS/feature/compose/ComposeViewModel.kt
- presentation/src/main/java/com/moez/QKSMS/feature/scheduled/ScheduledActivity.kt
- presentation/src/main/java/com/moez/QKSMS/feature/scheduled/ScheduledView.kt
- presentation/src/main/java/com/moez/QKSMS/feature/scheduled/ScheduledViewModel.kt
- presentation/src/main/res/menu/scheduled_messages.xml
- presentation/src/main/res/values/strings.xml
allows editing of scheduled messages via a new menu item on the scheduled messages activity.
this is stage 3 - and final - implementation of my feature request https://github.com/octoshrimpy/quik/issues/296. it includes prior stage 1 pr https://github.com/octoshrimpy/quik/pull/297 and stage 2 pr https://github.com/octoshrimpy/quik/pull/298.
new menu item on scheduled message activity available only when a single message is selected;
confirms the possible loss of message with a dialog;
then starts the compose activity with the scheduled message's data - schedule date/time, send as group, subscription id, threadId, attachments, text, recipients. user can then edit the message and 'send' (re-schedule) as usual.
closes https://github.com/octoshrimpy/quik/issues/296
> changes to allow editing of scheduled messages

- domain/src/main/AndroidManifest.xml
- domain/src/main/java/com/moez/QKSMS/extensions/UriExtensions.kt
- presentation/src/main/res/layout/attachment_file_list_item.xml
- presentation/src/main/res/layout/scheduled_message_image_list_item.xml
updated code used to fetch icons from other apps for compose box attachments. enabled access to other apps icons in manifest. small adjustment to text transparency to provide greater contrast between icon and text. made text in front of icon always black.
example attaching a pdf... before - generic attach icon because default pdf app icon wasn't accessible, and hard to see text;
after - uses icon from default installed pdf view app, and text easier to see;
[ edit: updated the pr with same visual changes to scheduled messages activity attachment icons ]
> Update attachment icon retrieve and manifest query to enable

- build.gradle
- presentation/src/main/java/com/moez/QKSMS/common/GlideCompletionListener.kt
upgrade glide library to v4.16.0 (latest non release candidate version at this time)
possibly helpful for issues relating to images including https://github.com/octoshrimpy/quik/issues/165
> upgrade glide library version

- presentation/src/main/java/com/moez/QKSMS/feature/compose/ComposeActivity.kt
- presentation/src/main/res/layout/compose_activity.xml
remove extraneous controls - sim and mic - when no reply possible in compose activity
closes https://github.com/octoshrimpy/quik/issues/304
closes https://github.com/octoshrimpy/quik/issues/299
> bug fix remove extraneous controls on compose (sim and mic) when no reply possible

- presentation/proguard-rules.pro
Added additional proguard rules to allow the backup and restore functionality to access files and start a foreground service. The reason it worked in QKSMS is because their backup and restore code was different and used a file path as a string and not a URI. To use the URI, the app needed Dagger and RxJava, which was blocked by proguard. I also added a rule that keeps the package name, to allow the foreground service to start up. 
Closes #70, 
Closes #148.
> Fix Backup and Restore being unable to read file.

- CONTRIBUTING.md
- README.md
This is the same file as the one I suggested in the wiki, does it look good? If there is a better way to build locally, I can change the build configuration example. It is generally recommended to have contributing guidelines within a repository, so I thought I would add it here along with the Wiki. Please let me know if you have any changes, and I apologize if I am being presumptuous in suggesting this. Thanks!
> Adds contributing guidelines.

- data/src/main/java/com/moez/QKSMS/receiver/BlockThreadReceiver.kt
change blockthreadreceiver db interaction to execute on an io thread.
closes https://github.com/octoshrimpy/quik/issues/308
> blockthreadreceiver db interaction on io thread

- presentation/src/main/java/com/moez/QKSMS/feature/qkreply/QkReplyViewModel.kt
fix circular update of message text and db conversation draft in qkreply causing cursor return to start of edit box
closes https://github.com/octoshrimpy/quik/issues/322
closes https://github.com/octoshrimpy/quik/issues/276
> fix circular update of message text and db conversation in qkreply

- presentation/src/main/java/com/moez/QKSMS/feature/compose/ComposeActivity.kt
- presentation/src/main/java/com/moez/QKSMS/feature/compose/ComposeView.kt
- presentation/src/main/java/com/moez/QKSMS/feature/compose/ComposeViewModel.kt
fix setting haserror (which is a bit  misused to finish() the compose activity) when sending from a new convo as group.
also fix associated bug that was sending sms to individual recipients in 'send as group mode' when send as group pref was saved as true.
possibly closes https://github.com/octoshrimpy/quik/issues/320
possibly closes https://github.com/octoshrimpy/quik/issues/338
this pr _may_ also fix https://github.com/octoshrimpy/quik/issues/335 and https://github.com/octoshrimpy/quik/issues/117 because some single-recipient messages may previously have been wrongly sent using the 'send as group' code path which does not necessarily match messages to existing conversations.
> fix bug causing compose activity to finish() when it wasn't supposed to

- data/src/main/java/com/moez/QKSMS/repository/MessageRepositoryImpl.kt
- domain/src/main/java/com/moez/QKSMS/repository/MessageRepository.kt
- presentation/src/main/java/com/moez/QKSMS/feature/compose/ComposeViewModel.kt
- presentation/src/main/java/com/moez/QKSMS/feature/main/MainViewModel.kt
- presentation/src/main/java/com/moez/QKSMS/feature/qkreply/QkReplyViewModel.kt
change to start dial of last 'not me' recipient in a conversation in compose, qkreply and main-activity-swipe call actions.
for single recipient convos nothing changes - the other convo party is dialled.
for group chats, convo messages are checked in reverse chrono order for the most previous message from 'not me' and that recipient is dialled. if a message from 'not me' is not found in the group convo, the present functionality is retained - ie  the first recipient listed in the group chat is dialled.
closes https://github.com/octoshrimpy/quik/issues/59
> dial last non-me party in a group convo

- presentation/build.gradle
- presentation/src/main/java/com/moez/QKSMS/feature/compose/ComposeActivity.kt
- presentation/src/main/java/com/moez/QKSMS/feature/compose/ComposeView.kt
- presentation/src/main/java/com/moez/QKSMS/feature/compose/ComposeViewModel.kt
fix no creation of a new conversation when no existing conversation to member of a multi-recipient sms not sent as group.
steps to reproduce existing bug;
1. compose new message to no recipients using floating '+' button on main activity
2. add a recipient with existing message(s) in their conversation
3. then also add a recipient with no existing messages/conversation
4. enter a message body
5. send >
6. check sent conversations list in main activity;
7. recipient with existing conversation will have sent message in their conversation
8. recipient with no existing conversation will not have a new conversation created with the new message
encountered this bug whilst testing for pr https://github.com/octoshrimpy/quik/pull/344
> fix new conversation not created for non-send-as-group multi-recipient message

- presentation/src/main/java/com/moez/QKSMS/common/util/extensions/ViewExtensions.kt
- presentation/src/main/java/com/moez/QKSMS/feature/compose/ComposeActivity.kt
- presentation/src/main/res/layout/compose_activity.xml
made background shade darker on compose activity (when attach menu activated and when audio record panel activated)
changed attach menu items to match back and fore theme of attach button
also fixed bug of attach button being touchable when audio record panel visible
closes https://github.com/octoshrimpy/quik/issues/336
new look - dark;
new look - light;
> ui changes to make attach menu properly visible in dark (and light) theme

- presentation/src/main/java/com/moez/QKSMS/feature/compose/ComposeState.kt
- presentation/src/main/java/com/moez/QKSMS/feature/compose/ComposeViewModel.kt
change to not save sms body input text as draft between adding new recipients to sms on compose screen.
solves issue below, but also in the following scenario;
1. click floating + button on main activity (new sms)
2. select a contact/existing convo
3. start typing text into sms body input box
4. add a new contact/existing convo
5. previously, the text entered before the second recipient was added was saved as draft in first added contact's convo, now it isn't
closes https://github.com/octoshrimpy/quik/issues/187
> do not save draft text when adding new recipients to group convo

- presentation/src/main/java/com/moez/QKSMS/feature/compose/MessagesAdapter.kt
change text selection handles and background colors in compose screen bubbles to use dynamic color values to ensure they always have a high contrast to bubble colours and to match with theme colors
note: selection handles can only have color changed in api 29+ / version_codes.q+. selected text background should always have color changed
closes https://github.com/octoshrimpy/quik/issues/248  which was experiencing some hot teal on teal action
examples. dark theme - teal;
dark theme - blue;
light theme - teal;
light theme - purple;
> ui - change compose activity bubble text selection colors

- presentation/src/main/java/com/moez/QKSMS/feature/compose/part/AudioBinder.kt
fix mediametadataretriever using autocloseable interface crash on api <= 29.
also update audio title background tint alpha to use extension func rather than mask
closes https://github.com/octoshrimpy/quik/issues/321#issuecomment-2726765764
> fix mediametadataretriever using autocloseable interface crash on api <= 29

- presentation/src/main/java/com/moez/QKSMS/common/base/QkRealmAdapter.kt
- presentation/src/main/java/com/moez/QKSMS/common/util/ClipboardUtils.kt
- presentation/src/main/java/com/moez/QKSMS/feature/compose/ComposeViewModel.kt
- presentation/src/main/res/values/strings.xml
speed up convo activity toggle (de)select all - particularly for large numbers of messages.
also speed up  copy text menu item on convo screen.
selection time...  before: 80790 msgs in 1m 3s.
after:
https://github.com/user-attachments/assets/cfe81599-af62-4142-9003-641ce7d3936c
> speed up convo activity (de)select all

- .github/workflows/build-on-pull.yml
This pr sets up the build-on-pull workflow to automatically upload an apk of each pull request. This will allow for easier testing and will help with debugging.
Satisfies [this request](https://github.com/octoshrimpy/quik/issues/269#issuecomment-2648448795) and [this comment](https://github.com/octoshrimpy/quik/pull/239#issuecomment-2691867028).
> Upload app apk to github

- domain/src/main/java/com/moez/QKSMS/util/Preferences.kt
- presentation/src/main/java/com/moez/QKSMS/common/base/QkActivity.kt
- presentation/src/main/java/com/moez/QKSMS/common/base/QkThemedActivity.kt
- presentation/src/main/java/com/moez/QKSMS/feature/settings/SettingsController.kt
- presentation/src/main/java/com/moez/QKSMS/feature/settings/SettingsPresenter.kt
- presentation/src/main/java/com/moez/QKSMS/feature/settings/SettingsState.kt
- presentation/src/main/res/drawable/ic_screenshot.xml
- presentation/src/main/res/layout/settings_controller.xml
- presentation/src/main/res/values/strings.xml
I added a setting to enable `SECURE_FLAG` for the app. This doesn't hide the app's contents immediately when in the app switcher but does disable screenshots. I am leaving it off by default as the conversation in #136 seemed to be leaning that way.
Closes #136
Closes #355
> Added a setting to disable screenshots.

- data/build.gradle
- data/src/main/java/com/moez/QKSMS/receiver/SmsReceiver.kt
- data/src/main/java/com/moez/QKSMS/worker/HousekeepingWorker.kt
- data/src/main/java/com/moez/QKSMS/worker/InjectionWorkerFactory.kt
- data/src/main/java/com/moez/QKSMS/worker/ReceiveSmsWorker.kt
- domain/src/main/java/com/moez/QKSMS/interactor/ReceiveSms.kt
- presentation/build.gradle
- presentation/src/main/AndroidManifest.xml
- presentation/src/main/java/com/moez/QKSMS/common/QKApplication.kt
- presentation/src/main/java/com/moez/QKSMS/injection/AppModule.kt
implement new receivesms worker.
modify sms receive interactor to be used by new worker and more logging.
create custom workfactory that supports injection into workers.
modify housekeeping worker to use injection.
possibly closes https://github.com/octoshrimpy/quik/issues/380
possibly closes https://github.com/octoshrimpy/quik/issues/384
> move sms receive code path to a worker model to avoid anr on message receive

- presentation/src/main/java/com/moez/QKSMS/feature/main/MainViewModel.kt
fixes a race condition in the main activity where selection was being cleared before block dialog had the list of selected convos
* stumbled upon this issue whilst testing for https://github.com/octoshrimpy/quik/pull/391
> fix race condition when using block menu item on main activity

- data/src/main/java/com/moez/QKSMS/manager/MediaRecorderManager.kt
- data/src/main/java/com/moez/QKSMS/util/Constants.kt
- data/src/main/java/com/moez/QKSMS/util/FileUtils.kt
- data/src/main/java/com/moez/QKSMS/worker/HousekeepingWorker.kt
- domain/src/main/AndroidManifest.xml
- domain/src/main/java/com/moez/QKSMS/extensions/LongExtensions.kt
- domain/src/main/java/com/moez/QKSMS/extensions/StringExtensions.kt
- domain/src/main/java/com/moez/QKSMS/model/Message.kt
- domain/src/main/res/xml/messages_text_file_provider_paths.xml
- presentation/src/main/java/com/moez/QKSMS/common/util/ClipboardUtils.kt
- presentation/src/main/java/com/moez/QKSMS/common/util/FileLoggingTree.kt
- presentation/src/main/java/com/moez/QKSMS/feature/compose/ComposeActivity.kt
- presentation/src/main/java/com/moez/QKSMS/feature/compose/ComposeState.kt
- presentation/src/main/java/com/moez/QKSMS/feature/compose/ComposeView.kt
- presentation/src/main/java/com/moez/QKSMS/feature/compose/ComposeViewModel.kt
- presentation/src/main/java/com/moez/QKSMS/feature/compose/MessagesAdapter.kt
- presentation/src/main/res/menu/compose.xml
- presentation/src/main/res/values/strings.xml
lots of point changes that flowed from limiting and sharing text feature;
limit bubble display of text to 5000 chars with ellipses.
add instruction status message when bubble char limit exceeded. add share text feature.
make copy and share text menu options only available when there is text in selected messages.
new FileProvider to share messages text files out of app's cache dir.
add message subject to copy messages text feature.
a lot of refactoring of MessagesAdapter class.
add new FileUtils class.
convert file logging to use new FileUtils class.
convert MediaRecorder to use new FileUtils class.
housekeeping worker now cleans messages text cache files.
housekeeping worker now checks cache files older than 2 hours before deleting. …
> limit convo bubble text to 5000 chars

- presentation/src/main/java/com/moez/QKSMS/feature/compose/ComposeAttachmentAdapter.kt
- presentation/src/main/java/com/moez/QKSMS/feature/compose/MessagesAdapter.kt
- presentation/src/main/java/com/moez/QKSMS/feature/extensions/CharSequenceExtensions.kt
- presentation/src/main/java/com/moez/QKSMS/feature/extensions/UriExtensions.kt
- presentation/src/main/java/com/moez/QKSMS/feature/scheduled/ScheduledMessageAttachmentAdapter.kt
changes to make emoji-only recognition faster.
old regex method was so slow that os would anr the process.
this change can be tested using the emoji string from issue https://github.com/octoshrimpy/quik/issues/183.
closes https://github.com/octoshrimpy/quik/issues/183
> make string parsing for emoji-only faster

- android-smsmms/build.gradle
- build.gradle
- data/build.gradle
- domain/build.gradle
- domain/src/main/java/com/moez/QKSMS/util/Preferences.kt
- presentation/build.gradle
- presentation/src/main/java/com/moez/QKSMS/common/QKApplication.kt
- presentation/src/main/java/com/moez/QKSMS/common/util/QkActivityResultContracts.kt
- presentation/src/main/java/com/moez/QKSMS/common/widget/QkEditText.kt
- presentation/src/main/java/com/moez/QKSMS/common/widget/QkTextView.kt
- presentation/src/main/java/com/moez/QKSMS/feature/backup/BackupController.kt
- presentation/src/main/java/com/moez/QKSMS/feature/compose/ComposeActivity.kt
- presentation/src/main/java/com/moez/QKSMS/feature/extensions/CharSequenceExtensions.kt
- presentation/src/main/java/com/moez/QKSMS/feature/qkreply/QkReplyActivity.kt
appcompat library to 1.6.1
remove deprecated androidx.emoji-appcompat - see https://developer.android.com/develop/ui/views/text-and-emoji/emoji-compat
use androidx.emoji2-bundled library (bundled for compatibility with non playstore/gsm os)
emoji2 compat library to 1.4.0 (required compilesdk upgrade to 34)
make qkedittext use appcompatedittext for emoji compatibility
fix small incompatibilities introduced by new library versions
* this pr overwrites and fixes previous pr https://github.com/octoshrimpy/quik/pull/399 which broke the app for non-playstore/gsm os's
> upgrades to appcompat and emoji libraries. fix pr 399 for non-playstore/gsm os

- presentation/src/main/java/com/moez/QKSMS/feature/compose/ComposeActivity.kt
- presentation/src/main/res/values-pl/strings.xml
- presentation/src/main/res/values-ro/strings.xml
- presentation/src/main/res/values/strings.xml
Fixes something brought up in #401. This makes the message on an STT error more clear.
> Rename error toast string

- presentation/src/main/java/com/moez/QKSMS/feature/compose/ComposeViewModel.kt
- presentation/src/main/java/com/moez/QKSMS/feature/main/MainViewModel.kt
use copied lists for non-main-thread tasks when followed by a clearSelections() call
> fix possible race conditions in main and compose activities

- data/src/main/java/com/moez/QKSMS/repository/MessageRepositoryImpl.kt
- domain/src/main/java/com/moez/QKSMS/interactor/CancelDelayedMessage.kt
- domain/src/main/java/com/moez/QKSMS/interactor/DeleteMessages.kt
- domain/src/main/java/com/moez/QKSMS/interactor/MarkRead.kt
- domain/src/main/java/com/moez/QKSMS/interactor/MarkUnread.kt
- domain/src/main/java/com/moez/QKSMS/interactor/ReceiveMms.kt
- domain/src/main/java/com/moez/QKSMS/interactor/ReceiveSms.kt
- domain/src/main/java/com/moez/QKSMS/repository/MessageRepository.kt
update messagerepo to keep congruence between app db messages and native provider when marking messages seen and read. previous code always threw an exception that was swallowed and didn't set anything in the native provider.
reformatting and small refactorings on mesasgerepo code.
* i saw somewhere - but don't recall where - someone mentioning that quik (or maybe qksms at the time) didn't set messages 'seen' properly and this was interacting badly with other sms apps. this pr should fix that.
> maintain setting messages seen and read congruence with native provider db

- presentation/src/main/AndroidManifest.xml
- presentation/src/main/java/com/moez/QKSMS/feature/compose/ComposeActivity.kt
- presentation/src/main/java/com/moez/QKSMS/feature/compose/ComposeView.kt
- presentation/src/main/java/com/moez/QKSMS/feature/main/MainActivity.kt
- presentation/src/main/java/com/moez/QKSMS/feature/main/MainView.kt
- presentation/src/main/java/com/moez/QKSMS/feature/main/MainViewModel.kt
- presentation/src/main/res/layout/main_activity.xml
edit: added some code cleanups and changes from wiggleforlifes testing.
change windowSoftInputMode="stateHidden" and remove some focusing code so keyboard not shown automagically on compose screen entry
edit:
* added requestfocus to search box on main actiivty layout. added  windowSoftInputMode="stateHidden" to stop keyboard being automagically shown on main activity load.
* cleaned up and refoctored some main activity code
* re-implemented setting focus to message box after sending sms on compose activity
this pr needs testing on a pure dpad device and also with touch screens. it is supposed to result in both dpad needing to click middle button to show keyboard (if it has on-screen keyboard), and for touch, to touch the input box to show keyboard.
below is a viddy of how this pr performs …
> no keyboard auto-show on compose activity

- presentation/src/main/res/values-fr/strings.xml
- add missing non-breaking changes
- change quotes
- change confirmation sentence
> fix: typo in French translation

- domain/src/main/java/com/moez/QKSMS/interactor/ReceiveSms.kt
- domain/src/main/java/com/moez/QKSMS/interactor/SendMessage.kt
- domain/src/main/java/com/moez/QKSMS/manager/ShortcutManager.kt
- presentation/src/main/java/com/moez/QKSMS/common/util/NotificationManagerImpl.kt
- presentation/src/main/java/com/moez/QKSMS/common/util/ShortcutManagerImpl.kt
- presentation/src/main/java/com/moez/QKSMS/common/util/extensions/ConversationExtension.kt
- presentation/src/main/java/com/moez/QKSMS/common/util/extensions/RecipientExtensions.kt
Hi, this is for #423
This PR add the necessary shortcuts to the system and to notifications so Android can enable it's conversation features for QUIK : notifications will be displayed on top, you can define priority convs and you can uses and android's default conversations widget.
I also added a Recipient.getThemedIcon function to get unified icons between notifications, launcher shortcuts and in app view.
This is also a first step for bubbles support, but some more work is needed.
> Enable Android conversation features

- domain/src/main/java/com/moez/QKSMS/manager/SpeakManager.kt
change "am" to "a m" and "pm" to "p m" in time read-out to fix for speech engines that pronounce "am" and "pm" as words rather than the individual letters.
locale aware for locales that don't use "am" and "pm."
also change read-out of "group sms" to "group message" for same reason.
> fix speech engines pronouncing "am" and "pm" and "sms" as words

- presentation/src/main/AndroidManifest.xml
Patches CVE-2024-3430. Brought up in #443. A big thank you to @MatejKovacic for the report. On critical applications, `allowBackup` should be set to false, to prevent the application from leaking it's data.
> Set allowBackup to false

- presentation/src/main/java/com/moez/QKSMS/feature/conversations/ConversationsAdapter.kt
- presentation/src/main/java/com/moez/QKSMS/feature/widget/WidgetAdapter.kt
- presentation/src/main/res/values/strings.xml
Fixes #457. Took a page out of Signal's book here and moved the draft indicator to the text snippet preview. This makes the previous groupchat issue irrelevant, but I also believe it's more consistent with how Quik indicates the user's outgoing messages. Currently they're indicated with `You: ...` while drafts have no prefix, which make it seem like an incoming message (especially when combined with the previously mentioned bug).
This is my first time taking a stab at android development, so would love to hear any feedback! Kotlin is a liiiiitle unfamiliar to me, along with this codebase. Cheers!
> Moved draft indicator to text snippet

- data/src/main/java/com/moez/QKSMS/util/ImageUtils.kt
fixes an intermittent error with glide using a recycled image from cache that resulted in mms send fail with no error reported
> fix glide 'using recycled image' error in resize mms image path

- CONTRIBUTING.md
- presentation/build.gradle
After commenting out that signing configs block 3 times in a row, I got sick of it and changed it to automatically use the debug keys. I basically had to force android studio to generate a debug key, and then move the keystore existence check to another area. If the keystore check is in the signing configs section, it fails every time. So I moved it to the bottom, and now everything works. 
I also removed the section in the contributing guidelines about this.
Can you double check that a release still builds? I am pretty sure it will, but am unable to test that. Thanks!
> Build debug build automatically with a debug key.

- presentation/src/main/java/com/moez/QKSMS/feature/main/MainActivity.kt
- presentation/src/main/java/com/moez/QKSMS/feature/main/MainView.kt
- presentation/src/main/java/com/moez/QKSMS/feature/main/MainViewModel.kt
- presentation/src/main/res/values/strings.xml
Previously it said that messages were archived when they actually were unarchived. The app no longer engages in this duplicity.
> Fix archived toast's incorrect wording

- presentation/src/main/java/com/moez/QKSMS/common/Navigator.kt
- presentation/src/main/java/com/moez/QKSMS/feature/conversationinfo/ConversationInfoAdapter.kt
- presentation/src/main/java/com/moez/QKSMS/feature/conversationinfo/ConversationInfoController.kt
- presentation/src/main/java/com/moez/QKSMS/feature/conversationinfo/ConversationInfoPresenter.kt
- presentation/src/main/java/com/moez/QKSMS/feature/conversationinfo/ConversationInfoView.kt
- presentation/src/main/java/com/moez/QKSMS/feature/main/MainActivity.kt
- presentation/src/main/java/com/moez/QKSMS/feature/main/MainViewModel.kt
- presentation/src/main/res/layout/conversation_info_settings.xml
- 3bf1e710225058335b36342ea0adf04cf84443d8: Makes changes so that both mark read and unread are present when multiple messages are selected
- 25f4716572f387b745e5fda31e4b57747a24f5b7: Adds an action to mark unread (and then navigate back to the main activity) from the conversation info
Closes #500
> Improvements to the mark (un)read actions

- data/src/main/java/com/moez/QKSMS/util/PhoneNumberUtils.kt
When QUIK receives a message it compares to see if it goes into a new conversation or an existing. However, if the numbers are formatted differently, it will think that they are separate convos. Hopefully, normalizing before comparing will fix that.
> Normalize numbers before comparing.

- data/src/main/java/com/moez/QKSMS/repository/MessageRepositoryImpl.kt
This is preferable to defaulting to the original name, as those are often not descriptive, or generic. Now they are saved with the format `QUIK_format_dateAndTime`.
Closes #499
> Change attachments to be saved with `QUIK_format_date`

- data/src/main/java/com/moez/QKSMS/migration/QkRealmMigration.kt
- data/src/main/java/com/moez/QKSMS/repository/ConversationRepositoryImpl.kt
- domain/src/main/java/com/moez/QKSMS/model/Conversation.kt
~~No idea, whether or not this actually fixes the issue, I am just guessing that a missing date was the problem.~~
Seems to have fixed it. Apparently, the date property wasn't getting passed to new conversation's drafts. (Maybe it was an Android 13 or e os thing)
Closes #513
Closes #431
> Fix draft being sorted at the bottom

- presentation/src/main/AndroidManifest.xml
- presentation/src/main/java/com/moez/QKSMS/feature/widget/WidgetAdapter.kt
- presentation/src/main/java/com/moez/QKSMS/feature/widget/WidgetProvider.kt
- presentation/src/main/res/values/strings.xml
This fixes an issue where system theme was not respected in the widget, upgrades some deprecated sections, and renames the widget title to `All Conversations` rather than `QUIK`.
Closes #34
> Various improvements to the widget

- data/src/main/java/com/moez/QKSMS/repository/SyncRepositoryImpl.kt
I am guessing that on large message db, sync could be unreliable hence the issue in #520. This speeds up the sync process, and makes it more robust
Closes #520
> Refactor sync code to use an async transaction/separate looper thread
